set nocompatible           
filetype plugin indent on  
syntax on                  
set backspace=2            
set autoindent             
set display=lastline       
set wildmenu               
set wildmode=list:longest  
set showcmd                
set smarttab               
set number                 
set wrap                   
set laststatus=2           
set ruler                  
set textwidth=80           
set nrformats-=octal       
set tabstop=4              
set shiftwidth=0           
set softtabstop=-1         
